wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.9
alpha:
  desc: null
  value: 0.2546297384239859
hidden_dim:
  desc: null
  value: 170
lr:
  desc: null
  value: 2.328253817582558e-05
n_graph_iters:
  desc: null
  value: 6
network:
  desc: null
  value: Edge_Track_Truth_Net
optimizer:
  desc: null
  value: Adam
step_size:
  desc: null
  value: 60
train_size:
  desc: null
  value: 368
weight_decay:
  desc: null
  value: 0.0009519471018374282
