wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.9
epochs:
  desc: null
  value: 198
hidden_dim:
  desc: null
  value: 60
lr:
  desc: null
  value: 0.0010998056123547838
n_graph_iters:
  desc: null
  value: 4
network:
  desc: null
  value: Edge_Track_Truth_Net
optimizer:
  desc: null
  value: AdamW
train_size:
  desc: null
  value: 171
weight_decay:
  desc: null
  value: 5.067397328613272e-05
