wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.19
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
epochs:
  desc: null
  value: 176
hidden_dim:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.001248050682281777
n_graph_iters:
  desc: null
  value: 5
network:
  desc: null
  value: Edge_Track_Truth_Net
optimizer:
  desc: null
  value: AdamW
train_size:
  desc: null
  value: 708
weight_decay:
  desc: null
  value: 0.0038718160677088842
