wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.9
alpha:
  desc: null
  value: 0.8996607646587464
hidden_dim:
  desc: null
  value: 236
lr:
  desc: null
  value: 0.01757067890148769
n_graph_iters:
  desc: null
  value: 10
network:
  desc: null
  value: Edge_Track_Truth_Net
optimizer:
  desc: null
  value: Adam
step_size:
  desc: null
  value: 25
train_size:
  desc: null
  value: 171
weight_decay:
  desc: null
  value: 0.00018316544726140887
