wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.19
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim:
  desc: null
  value: 25
hops:
  desc: null
  value: 4
lr:
  desc: null
  value: 4.4215466495322124e-05
n_graph_iters:
  desc: null
  value: 2
network:
  desc: null
  value: Edge_Track_Truth_Net
optimizer:
  desc: null
  value: AdamW
train_size:
  desc: null
  value: 398
weight_decay:
  desc: null
  value: 2.0095272849249792e-05
