wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.9
alpha:
  desc: null
  value: 0.48951620742142726
hidden_dim:
  desc: null
  value: 56
lr:
  desc: null
  value: 0.0029574944738364867
n_graph_iters:
  desc: null
  value: 8
network:
  desc: null
  value: Edge_Track_Truth_Net
optimizer:
  desc: null
  value: Adam
step_size:
  desc: null
  value: 44
train_size:
  desc: null
  value: 466
weight_decay:
  desc: null
  value: 8.128482261397266e-05
