wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.9
epochs:
  desc: null
  value: 206
hidden_dim:
  desc: null
  value: 80
lr:
  desc: null
  value: 0.0019509450014441824
n_graph_iters:
  desc: null
  value: 3
network:
  desc: null
  value: Edge_Track_Truth_Net
optimizer:
  desc: null
  value: AdamW
train_size:
  desc: null
  value: 335
weight_decay:
  desc: null
  value: 0.00010403123724988512
