wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    framework: torch
    is_jupyter_run: true
    python_version: 3.6.9
alpha:
  desc: null
  value: 0.3335839600177283
hidden_dim:
  desc: null
  value: 141
lr:
  desc: null
  value: 0.0012987562183157852
n_graph_iters:
  desc: null
  value: 9
network:
  desc: null
  value: Edge_Track_Truth_Net
optimizer:
  desc: null
  value: Adam
step_size:
  desc: null
  value: 87
train_size:
  desc: null
  value: 444
weight_decay:
  desc: null
  value: 0.00010466565986616468
