wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.9
epochs:
  desc: null
  value: 114
hidden_dim:
  desc: null
  value: 56
lr:
  desc: null
  value: 0.008054860273654242
n_graph_iters:
  desc: null
  value: 4
network:
  desc: null
  value: Edge_Track_Truth_Net
optimizer:
  desc: null
  value: Adamax
train_size:
  desc: null
  value: 146
