wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.19
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim:
  desc: null
  value: 10
hops:
  desc: null
  value: 3
lr:
  desc: null
  value: 5.50918959877485e-05
n_graph_iters:
  desc: null
  value: 7
network:
  desc: null
  value: Edge_Track_Truth_Net
optimizer:
  desc: null
  value: AdamW
train_size:
  desc: null
  value: 505
weight_decay:
  desc: null
  value: 1.6610316128001928e-05
