wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.19
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.9
hidden_dim:
  desc: null
  value: 58
hops:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.00021045702600248748
n_graph_iters:
  desc: null
  value: 2
network:
  desc: null
  value: Edge_Track_Truth_Net
optimizer:
  desc: null
  value: AdamW
train_size:
  desc: null
  value: 601
weight_decay:
  desc: null
  value: 5.30754340022338e-05
