wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    framework: torch
    is_jupyter_run: true
    python_version: 3.6.9
alpha:
  desc: null
  value: 0.7090954625603817
hidden_dim:
  desc: null
  value: 86
lr:
  desc: null
  value: 0.06159639196071422
n_graph_iters:
  desc: null
  value: 9
network:
  desc: null
  value: Edge_Track_Truth_Net
optimizer:
  desc: null
  value: Adam
step_size:
  desc: null
  value: 65
train_size:
  desc: null
  value: 637
weight_decay:
  desc: null
  value: 1.9481379878969436e-05
