wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    framework: torch
    is_jupyter_run: true
    python_version: 3.6.9
alpha:
  desc: null
  value: 0.6431405485905626
hidden_dim:
  desc: null
  value: 193
lr:
  desc: null
  value: 0.0012450083550865723
n_graph_iters:
  desc: null
  value: 5
network:
  desc: null
  value: Edge_Track_Truth_Net
optimizer:
  desc: null
  value: Adam
step_size:
  desc: null
  value: 21
train_size:
  desc: null
  value: 505
weight_decay:
  desc: null
  value: 0.00046700996798401846
