name: base
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - pip=19.2.3
  - pytorch=1.2.0
  - pip:
    - torch-cluster==1.4.4
    - torch-geometric==1.3.1
    - torch-scatter==1.3.1
    - torch-sparse==0.4.0
    - seaborn==0.9.0
    - ipython==7.8.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - matplotlib==3.1.1
    - PyYAML==5.1.2