name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - seaborn=0.9.0
  - widgetsnbextension=3.5.1
  - wheel=0.33.4
  - Werkzeug=0.16.0
  - webencodings=0.5.1
  - wcwidth=0.1.7
  - typing=3.6.4
  - traitlets=4.3.2
  - tornado=6.0.3
  - torch=1.2.0a0+8554416
  - torch-sparse=0.4.0
  - torch-scatter=1.3.1
  - torch-geometric=1.3.0
  - torch-cluster=1.4.4
  - testpath=0.4.2
  - terminado=0.8.2
  - tensorboard=2.0.0
  - six=1.12.0
  - setuptools=41.0.1
  - Send2Trash=1.5.0
  - scipy=1.3.0
  - scikit-learn=0.21.2
  - rdflib=4.2.2
  - pyzmq=18.0.0
  - PyYAML=5.1.1
  - pytz=2019.1
  - python-dateutil=2.8.0
  - pyrsistent=0.15.4
  - pyparsing=2.4.0
  - Pygments=2.4.2
  - pycparser=2.19
  - ptyprocess=0.6.0
  - protobuf=3.10.0
  - prompt-toolkit=2.0.9
  - prometheus-client=0.7.1
  - plyfile=0.7
  - pip=19.1.1
  - Pillow=6.1.0
  - pickleshare=0.7.5
  - pexpect=4.7.0
  - parso=0.5.0
  - pandocfilters=1.4.2
  - pandas=0.25.0
  - olefile=0.46
  - numpy=1.16.4
  - notebook=6.0.0
  - networkx=2.3
  - nbformat=4.4.0
  - nbconvert=5.6.0
  - mkl-service=2.0.2
  - mkl-random=1.0.2
  - mkl-fft=1.0.12
  - mistune=0.8.4
  - matplotlib=3.1.0
  - MarkupSafe=1.1.1
  - Markdown=3.1.1
  - kiwisolver=1.1.0
  - jupyter-core=4.5.0
  - jupyter-client=5.3.1
  - jsonschema=3.0.2
  - joblib=0.13.2
  - Jinja2=2.10.1
  - jedi=0.13.3
  - isodate=0.6.0
  - ipywidgets=7.5.1
  - ipython=7.7.0
  - ipython-genutils=0.2.0
  - ipympl=0.2.1
  - ipykernel=5.1.1
  - h5py=2.9.0
  - grpcio=1.24.3
  - entrypoints=0.3
  - defusedxml=0.5.0
  - decorator=4.4.0
  - cycler=0.10.0
  - cffi=1.12.3
  - certifi=2019.6.16
  - bleach=3.1.0
  - backcall=0.1.0
  - attrs=19.1.0
  - absl-py=0.8.1
  - torchvision=0.3.0