wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.9
alpha:
  desc: null
  value: 0.2144729224820346
hidden_dim:
  desc: null
  value: 174
lr:
  desc: null
  value: 9.702373197477014e-05
n_graph_iters:
  desc: null
  value: 2
network:
  desc: null
  value: Edge_Track_Truth_Net
optimizer:
  desc: null
  value: Adam
step_size:
  desc: null
  value: 42
train_size:
  desc: null
  value: 632
weight_decay:
  desc: null
  value: 0.0001681228519041128
